vich_uploader:
    db_driver: orm

    mappings:
       product_images:
           uri_prefix: '%app.path.product_images%'
           upload_destination: '%app.path.product_images%'
           namer: Vich\UploaderBundle\Naming\UniqidNamer